### ISSUE TITLE
Question on Flask Tutorial: Simple User Registration and Login

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#25]
##### **Overview of the issue**

Question from [Yousef Shanawany](http://disq.us/p/1ypsrb5):

> We completed this tutorial and got our application running with authentication working. However, users are logged out automatically sometimes and we don't want this to happen. Is the timeout length set somewhere? How can we modify it?

@rdegges Can you please answer this when you get a chance?

**Comment by mraible** [comment]
Another issue reported by [Gilad Katan](http://disq.us/p/238g33v):

> Awesome, it is working - but! only on localhost.
> 
> I tried now to change the configurations so it will work on my public website and it is > not working.
> I created a new application (in okta's UI), filled my url instead of localhost:5000:
> 1. "Login redirect URIs ": "http://app.mywebsite.com/oidc/callback"
> 2. "Initiate login URI": "http://app.mywebsite.com/oidc/callback"
> 
> I changed the client id, the secret and the redirect_uris within the json file with the new values and it is not working. I'm getting 500 Internal Server Error page.
> 
> What am I missing? Thanks!

**Comment by rdegges** [comment]
Answered them all.
