### ISSUE TITLE
Bug in Tutorial: Build a Basic CRUD App with Symfony 4 and Vue

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#29]
##### **Overview of the issue**

Issue reported by [theo](https://developer.okta.com/blog/2018/06/14/php-crud-app-symfony-vue#comment-4281626062):

> Hello !
> 1 question: in components/MoviesList.vue
> I have two root elements in my template, so how can i fix it ?
> Thanks in advance

Can you please have a look and see if you can assist @aaronpk?

**Comment by aaronpk** [comment]
Not sure I understand the question, but I replied anyway.
