### ISSUE TITLE
Clarification requested on Use OpenID Connect for Authorization in Your ASP.NET MVC Framework 4.x App

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#34]
##### **Overview of the issue**

From [Matthew](http://disq.us/p/1z7b4ll):

> This is a little confusing as some of the recommended things do not appear in the source code. One example is the http://localhost:8080/authorization-code/callback, which doesn't seem to be a valid path on the site. Another one is the part where you're talking about mapping the openid connect groups to roles. Can we get clarification?

**Comment by leebrandt** [comment]
Answered comment.
