### ISSUE TITLE
Questions in Add Social Login to Your Spring Boot 2.0 App

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#35]
##### **Overview of the issue**

Several questions about this post from [Ela](https://developer.okta.com/blog/2018/07/24/social-spring-boot#comment-4306357249):

> 1. It was announced Google+ is being shut down. It would be nice to mention how those this affect authentication and fact you have to enable google+ api to use Google as id provider.
> 2. I had problems adding redirect url at google api. Provided value was not saved. I hacked it by providing two urls (of which only first one was saved).
> 3. The tutorial note "If your social accounts use an email address different than what you’re using for your Okta preview account, you may need to add a user to the Okta application." suggests you need to create users first. It did not happen to me (for google), octa user was created by logging in. It would be worth mentioning what to disable this kind of registration.

**Comment by bdemers** [comment]
done
