### ISSUE TITLE
Bugs reported in How to Secure Your .NET Web API with Token Authentication

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#40]
##### **Overview of the issue**

Reported by [Kelly J](http://disq.us/p/1vbhak5) 5 months ago:

> Having an issue getting this demo to work. I believe I've followed everything correctly, but I get a status code of "Unauthorized" when I retrieve the Values. Currently banging my head against the wall on that.
>
> On a lark, I tried navigating to "https://dev-502773.oktaprev..." in a browser, which is the URL that we are to put in the ConfigureServices() method in the API, and get a 404 error that way. Is that something expected or is something currently down?

goobering provided [a fix](http://disq.us/p/1vek2x8).

This post should probably be updated with the fix.

**NOTE:** There's also readers asking for a .Net Core 2.2 version, and a .NET Framework version of this article. It'd be good to respond with existing articles, or tell them we'll consider it for feature posts (or not).

**Comment by leebrandt** [comment]
https://github.com/okta/okta.github.io/pull/2736 should fix the issue from this comment. I also responded to comments about different versions. Should be a .NET Framework post out in the next week or so.
