### ISSUE TITLE
Bug in Add Authentication to Any Web Page in 10 Minutes

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#41]
##### **Overview of the issue**

Kevin [reported an issue](http://disq.us/p/1zil102):

> When I attempt to login through the site on localhost:8080 which I built with your tutorial, I get the error message:
> 
> "There was an unexpected internal error. Please try again." and the python server which is running in my terminal I get "code 501, message Unsupported method ('POST'). Any advice is greatly appreciated! Thanks.

**Comment by mraible** [comment]
This one received a comment last week from [Erik](http://disq.us/p/20vqngz):

> Getting a "Unable to connect to the server. Please check your network connection." when trying to login with these instructions (and Gaurav below).

Another comment was received today from [Jasbir B](http://disq.us/p/211au4c)

> I tried the instructions but just get "Unable to connect to the server. Please check your network connection."
> 
> I granted Cross-origin access to the base URL of the website, but this did not make a difference. The online Test failed too.

**Comment by rdegges** [comment]
This is so lame. Apparently we took down old versions of the widget... Broke EVERYTHING.

**Comment by rdegges** [comment]
OK. This one is fixed. I talked to Robert + Nate and they were able to re-load the old missing versions of the widget onto the CDN. Whew.
