### ISSUE TITLE
Issues reported in Use TypeScript to Build a Node API with Express

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#46]
##### **Overview of the issue**

Reported by [SomeGuy54321](http://disq.us/p/20hi0bf):

> I found vscode was complaining about `req.logout()` not being a property on the express.Request type. Installing `@types/passport` and assing `"passport"` to the `"types"` list of `tsconfig.json` fixed it.

Reported by [Kc Sahoo](http://disq.us/p/20pjpdy):

> Works perfectly if one follows exact steps.
> Only one change:
> replace this part 
```
<tbody>
<tr v-for="guitar in guitars">
<td></td>
<td></td>
<td></td>
<td></td>
<td>
<button id="guitarDelete" @click="confirmDeleteGuitar(guitar.id)" class="btn-small">deleteDelete</button>
</td>
</tr>
</tbody>
```

> with

```
<tbody>
<tr v-for="guitar in guitars">
<td>{{guitar.year}}</td>
<td>{{guitar.brand}}</td>
<td>{{guitar.model}}</td>
<td>{{guitar.color}}</td>
<td>
<button id="guitarDelete" @click="confirmDeleteGuitar(guitar.id)" class="btn-small">deleteDelete</button>
</td>
</tr>
</tbody>
```

**Comment by reverentgeek** [comment]
The `req.logout()` is not an issue if you use the code that is in the post. The post doesn't use `passport`. The `logout()` error is only if the reader takes the suggestion of one of the other comments and strongly types the `req` object. If we had type definitions for Okta, then we could add those type definitions and strongly type the `req` object to recognize `.logout()` as a valid function.

It just so happens that `passport` adds a `logout()` function to the request object.
