### ISSUE TITLE
Bug reported in Add Authentication to your PHP App in 5 Minutes

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#47]
##### **Overview of the issue**

A bug has been reported twice by two separate readers. The latest is from [Darren Quigley](http://disq.us/p/20pir8z):

> Getting same error as below, it was then saying "The+authorization+server+resource+does+not+have+any+configured+default+scopes%2C+%27scope%27+must+be+provided."
> If I add in username as a default scope I then get -> Authorization server returned an invalid state parameter

**Comment by aaronpk** [comment]
I forgot that my authorization server was set to include a default scope. I'll update the blog post to add that instruction.
