### ISSUE TITLE
Bug reported in Build a Simple CRUD App with ASP.NET Core and Vue

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#49]
##### **Overview of the issue**

Reported by [Keith Lewis](https://developer.okta.com/blog/2018/08/27/build-crud-app-vuejs-netcore#comment-4382734014) and there are **32** upvotes on his comment!

> I noticed some issues with the FoodRecords.vue. your code shows the b-alert element with an extra space between the colon and show but it should look like this:

```
<b-alert :show="loading" variant="info">Loading...</b-alert>
```

> This also happens in b-card element between colon and title where it should be:

```
<b-card :title="(model.id ? 'Edit Food ID#' + model.id : 'New Food Record')">
```

> and in the tr for the table where it should be:

```
<tr v-for="record in records" :key="record.id">
```

Also reported by [Phillip Grigoryev](http://disq.us/p/20hd77i):

> Weird thing, when I try to open FoodTracker page, it comes empty.

##### **Related issues**

https://github.com/oktadeveloper/okta-blog/issues/22

**Comment by leebrandt** [comment]
[PR](https://github.com/okta/okta.github.io/pull/2821) fixed issues.
