### ISSUE TITLE
Issue with Build a Basic CRUD App with Laravel and Angular

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#55]
##### **Overview of the issue**

Comment from [db](http://disq.us/p/21kzn8u):

> Hey, having some troubles with this step Secure the Backend API with Okta.
> Can anyone help me with that?
> Here's the [link](https://stackoverflow.com/questions/55983618/response-with-status-401-unauthorized-for-url-laravel-angular-okta)

I'll ask Krasimir if he can help.

**Comment by aaronpk** [comment]
He updated his SO question with the solution he found. 

https://stackoverflow.com/q/55983618
