### ISSUE TITLE
Issue reported in Build a Secure Node.js App with SQL Server

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#80]
##### **Overview of the issue**

From [remaind](http://disq.us/p/23p0i1t):

> This is a great walkthrough, at least as a start...The beginning of it works great, however, I'm running into an issue integrating Okta in the last part...I'm getting a CORS error after authenticating initially:
Access to XMLHttpRequest at 'https://[myurl].okta.com/oauth2/v1/authorize?client_[stuff] (redirected from 'https://localhost:8080/api/events') from origin 'https://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
In chrome, so I think it has to do with the headers being sent by the hapi server rather than Okta. (I added a TLS cert in the hopes that maybe that was the issue). I added routes:{cors:true} to the Hapi.server config object in server.js...but it doesn't seem like it's doing anything.

> Any insight into why this might be coming up?

**Comment by reverentgeek** [comment]
> Hi remaind ! Thanks for taking the time to walk through the tutorial! I just stepped through the tutorial from scratch to make sure I didn't miss anything, and it's working for me. I believe it might be a configuration issue. Check your Okta Application Settings to see if the correct URIs are listed that match your local web application. For example: https://www.screencast.com/... Also, check your .env file settings. The Okta org url should look like https://dev-123123.oktaprev... with "oktapreview" instead of "okta." The client ID and secret should be alphanumeric strings without the curly braces. Hope this helps!
